### ISSUE TITLE
TypeError: Cannot read property 'decode' of undefined

### ISSUE THREAD

**Issue by AndreMiras** [AndreMiras/etheroll#32]
https://sentry.io/andre-5t/etheroll-fe/issues/796192163/?referrer=github_plugin

```
TypeError: Cannot read property 'decode' of undefined
  at decodeEvent (utils/etheroll-contract.js:63:61)
  at None (utils/etheroll-contract.js:129:55)
  at Array.map (<anonymous>)
  at callback (utils/etheroll-contract.js:129:38)
  at None (chrome-extension://cickkggoijngnjkmbmkibdhmklahopfi/inpage.js:1:99728)
...
(41 additional frame(s) were not displayed)
```

**Comment by AndreMiras** [comment]
Sentry issue: [ETHEROLL-FE-Y](https://sentry.io/andre-5t/etheroll-fe/issues/824099667/?referrer=github_plugin)

**Comment by AndreMiras** [comment]
Adding extra data to the Sentry trace might be helpful, see `setExtra()` https://blog.sentry.io/2019/01/17/debug-tough-front-end-errors-sentry-clues
