### ISSUE TITLE
TypeError: Cannot read property 'PlayerNumber' of undefined

### ISSUE THREAD

**Issue by AndreMiras** [AndreMiras/etheroll#60]
https://sentry.io/organizations/andre-5t/issues/1342188142/?referrer=github_plugin

```
TypeError: Cannot read property 'PlayerNumber' of undefined
  at None (components/CoinFlipTransactions.jsx:81:34)
  at Array.filter (<anonymous>)
  at c (components/CoinFlipTransactions.jsx:80:45)
  at setState (components/CoinFlip.jsx:35:35)
  at filterTransactions (components/BaseGame.jsx:158:5)
...
(41 additional frame(s) were not displayed)
```

**Comment by AndreMiras** [comment]
Fixed via 7cf4dd3c66640b526205e457a7f516ff0b1c56de
